# Generated by Django 5.0.6 on 2024-07-05 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_completed_task_created_task_title_task_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
